# Generated by Django 4.2 on 2025-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Numeric score out of 100', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credits', models.IntegerField(default=0)),
                ('academic_year', models.CharField(default='2023-2024', max_length=20)),
                ('semester', models.CharField(default='All', max_length=20)),
                ('is_official', models.BooleanField(default=True)),
            ],
        ),
    ]
