# Generated by Django 4.2 on 2025-11-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignment_score',
            field=models.PositiveIntegerField(blank=True, help_text='Assignment score (max 20)', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_exam_score',
            field=models.PositiveIntegerField(blank=True, help_text='Final exam score (max 50)', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='mid_score',
            field=models.PositiveIntegerField(blank=True, help_text='Midterm score (max 25)', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz_score',
            field=models.PositiveIntegerField(blank=True, help_text='Quiz score (max 5)', null=True),
        ),
    ]
