# Generated by Django 4.2 on 2025-11-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('ai_advisor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecommendation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='subjects.subject'),
        ),
    ]
